#!/bin/sh
set -x

#    Generate grasp2K expansions
#    1s(2)2s n=3 CAS
#    split into blocks

$GRASP/bin/jjgen << EOF


3
d


2

2
1
0
1,1
3

EOF

cp clist.log 2s_3.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

