#!/bin/sh
set -x

#  1.  Generate grasp2K expansions
#      1.1 HF for 2s2p 1P,3P
#          This case is easiest with csl

$GRASP/bin/csl << EOF
y
1s
2*
n
n
2s(1)2p(1)


0
EOF

mv rcsl.out rcsl.inp
$GRASP/bin/jsplit << EOF
n
EOF

mv rcsl.out odd2.c

#        1.2 SDT for n=3 but 1s always singly occupied

$GRASP/bin/jjgen <<EOF
*
*
3
d
*
y
1
1
2
*
2
1
1
0,4
3
*
EOF

mv clist.out rcsl.inp
$GRASP/bin/jsplit <<EOF
n
EOF

mv rcsl.out odd3.c

#      	  1.3  SDT for n=3,4 but at most 2 n=4

$GRASP/bin/jjgen <<EOF
*
*
4
f
*
y
1
1
2
2
*
2
1
1
0,4
3
*
EOF

mv clist.out rcsl.inp
$GRASP/bin/jsplit <<EOF
n
EOF

mv rcsl.out odd4.c


#      	  1.4  SDT for n=3,4,5 but at most 2 n=4,5

$GRASP/bin/jjgen <<EOF
*
*
5
g
*
y
1
1
2
2
2
*
2
1
1
0,4
3
*
EOF

mv clist.out rcsl.inp

$GRASP/bin/jsplit <<EOF
n
EOF

mv rcsl.out odd5.c

