#!/bin/sh
set -x

#   Generate odd parity MCHF set A from Migdalek 1991
# 4f14 6s1 6p1 J=0,2
# 4f14 6p1 5d1 J=0,4
#   Generate even parity MCHF set from Migdalek 1991 
# 4f14 6s2
# 4f14 6p2
# 4f14 5d2

$GRASP/bin/jjgen << EOF


6
f


6
c
5
14
0
0
1
1
0
0
0,4
1
y
6
f


6
14
1
0
0
1
0
0
0,8
1
y
6
f


6
14
0
0
2
0
0
0
0,0
1
y
6
f


6
14
0
0
0
2
0
0
0,6
1
y
6
f


6
14
0
0
0
0
2
0
0,10
1

EOF

cp clist.log 6s_6p_5d_4f.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

