#!/bin/sh
set -x

#   Generate grasp2K expansions
#   [Xe]4f14 closed, CI with 2 excitations
#   J = 0,0 (lower,upper)
#   split into blocks

$GRASP/bin/jjgen << EOF


6
f
n

6
c
5
14
c
0

0

2

0

0

0

0,0
2

EOF

cp clist.log 2s_2p_DF.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

