#!/bin/sh
set -x

#   Generate grasp2K expansions
#   [Xe]4f14 5d10 6s2 ; S ; 2J = 0,0
#   [Xe]4f14 5d10 6s1 6p1; S; 2J = 2,4
#   7+284 S configs

$GRASP/bin/jjgen << EOF


6
f


6
c
5
14
10
0
2
0
0
0
0,0
1
y
6
f


6
14
10
0
1
1
0
0
2,4
1

EOF

cp clist.log 2s_2p_DF.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

