#!/bin/sh
set -x

#   6s2, 6s6p (J = 0-4), 6s5d (J = 1-3), 4f13 6s2 5d (J = 1,6)

$GRASP/bin/jjgen << EOF


7
f
 

6
c
5
14
0
0
2
0
0
0
0,0
0
y
7
f


6
14
0
0
1
1
0
0
0,4
0
y
7
f


6
14
0
0
1
1
0
0
2,2
0
y
7
f


6
14
1
0
1
0
0
0
2,6
0
y
7
f


6
13
1
0
2
0
0
0
2,12
0

EOF

cp clist.log 6s_6p_5d_4f.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

