#!/bin/sh
set -x

# Biorthogonal transformation

$GRASP/bin/biotra3 > out_biotra <<EOF
y
y
2s_3
2p_3
y
EOF

# Then the transition calculations

$GRASP/bin/bioscl3 > out_bioscl <<EOF
y
n
2s_3
2p_3
E1
EOF


