#!/bin/sh
set -x

#   Generate grasp2K expansions for initial DF run
#   First Config: 1S1/2
#   Closed: [Xe]
#   Active: 4f14 5d0 5f0 6s1 6p0 6d0 6f0 
#   2*J = 1,1 (lower,upper)
#   0 excitations

#   split into blocks

$GRASP/bin/jjgen << EOF


6
f
n

6
c
5
14

0

0

1

0

0

0

1,1
0
y
6
f
n

6
14

0

0

0

1

0

0

1,3
0


EOF

cp clist.log 6s_6p_DF.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

