#!/bin/sh
#set -x

#    Generate grasp2K expansions
#    [Xe] max n=6 CAS since n=7 shells are far higher 
#    SD excitations, 4f has at least 13 electrons
#    Ref config is 4f14 6s1

$GRASP/bin/jjgen << EOF


6
f
n

6
c
5
14
13
0

0

1

0

0

0

1,3
2


EOF

cp clist.log 6s_7.log
cp clist.out rcsl.inp

$GRASP/bin/jsplit << EOF
n
EOF

cp rcsl.out rcsl.inp

