#!/bin/sh
set -x

# Perform self-consistent field calculations
# ...with extended optimal level weighting (idk what that means)
$GRASP/bin/rscf2 > out_scf_6s_6p_DF <<EOF
y
y
1
1
1
5
6s 6p- 6p 4f- 4f
6s 6p-
1000
EOF

$GRASP/bin/rsave 6s_6p_DF
less ./out_scf_6s_6p_DF
