#!/bin/bash

# Run existing calculation scripts and saves...
# 1) Script contents
# 2) Output of GRASP
# 3) RLEVELS output
less script_6s2_6s6p.out > script_6s2_6s6p.out
less script_1S0 > script_1S0.out
less script_1P1 > script_1P1.out

./script_6s2_6s6p |& tee -a script_6s2_6s6p.out
./script_1S0 |& tee -a script_1S0.out
./script_1P1 |& tee -a script_1P1.out
rlevels 1S0.cm 1P1.cm |& tee -a script_1S0.out
rlevels 1S0.cm 1P1.cm |& tee -a script_1P1.out
