#!/bin/bash

# Multiref: 6s2, 4f13 6s2 5d, 4f14 6s 6p, 0 exc.
# Orbitals: 6s, 6p, 5d, 4f
# user-defined order of orbitals in clist.ref
rnucleus_input="rnucleus_input_Z70"
rnucleus < $rnucleus_input
cat $rnucleus_input
rcsfgenerate_input="rcsfgenerate_input_both"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log both.exc
cp rcsf.out rcsf.inp
cp rcsf.out rcsfmr.inp
printf 'y' | rangular

# optimize 4f* orbitals
rwfnestimate_input="rwfnestimate_input_from_1P1"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_both" 
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
# optimize 5d*, 6s, 6p*
rwfnestimate_input="rwfnestimate_input_both"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_both_2" 
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
# optimize 4f* 5d* 6s 6p*
rwfnestimate_input="rwfnestimate_input_both"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_both_3" 
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
rsave both

# Multiref: 6s2, 4f13 6s2 5d, 4f14 6s 6p, 1 exc.
# Orbitals: 7s, 7p, 6d, 5f
rcsfgenerate_input="rcsfgenerate_input_both_2"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log both.exc
cp rcsf.out rcsf.inp
printf '1' | rcsfinteract
cp rcsf.out rcsf.inp
printf 'y' | rangular
rwfnestimate_input="rwfnestimate_input_append_rwfnout"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_both_4"
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
rsave both
# 
# #2. add active orbitals: layer 1-1 (7s)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_2"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_12"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#3. add active orbitals: layer 1-2 (7p)
# convergence problsm at mcdhf, try 7p first then 5f
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_3"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_3"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
# rmcdhf_input="rmcdhf_input_1P1_13"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#3. add active orbitals: layer 1-2 (5f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_3"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_13"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input

#3. add active orbitals: layer 1-3 (5g)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_4"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_4"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input

#4. add active orbitals: layer 2-1 (8s,6d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_5"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_5"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#5. add active orbitals: layer 2-2 (8p,6f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_6"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_6"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#6. add active orbitals: layer 3-1 (9p,7f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_7"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_7"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#7. add active orbitals: layer 3-2 (9s,7d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_8"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_8"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#8. add active orbitals: layer 3-2 (6g)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_9"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_9"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#9. add active orbitals: layer 4-1 (8d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_10"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_10"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#10. add active orbitals: layer 4-1 (8f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_11"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_11"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
# rsave 1P1

# Final Step. vary all orbitals:

rnucleus_input="rnucleus_input_Z70"
rnucleus < $rnucleus_input
cat $rnucleus_input
rcsfgenerate_input="rcsfgenerate_input_"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log both.exc
cp rcsf.out rcsf.inp
printf '1' | rcsfinteract
cp rcsf.out rcsf.inp
printf 'y' | rangular
rwfnestimate_input="rwfnestimate_input_both"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_both_all"
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
rsave both

stateID="both"
rsave $stateID
# printf "1\n$stateID.w\n$stateID.w.readrwf" | readrwf
#printf "$stateID\nn\n0\ny" | rmixextract |& tee $stateID.rmix # DHF

# CI
rci_input="rci_input_1P1"
rci < $rci_input
cat $rci_input
#printf "$stateID\ny\n0\ny" | rmixextract |& tee $stateID.crmix # CI

# jj2lsj
jj2lsj_input="jj2lsj_input_1P1"
jj2lsj < $jj2lsj_input
cat $jj2lsj_input





