#!/bin/bash

#1. Yb core ([Xe]4f14) + 6s6p 1P1
# user-defined order of orbitals in clist.ref
# separate 5d1 out from previous calculation (script_6s2_6s6p)
rnucleus_input="rnucleus_input_Z70"
rnucleus < $rnucleus_input
cat $rnucleus_input
rcsfgenerate_input="rcsfgenerate_input_1P1"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log 1P1.exc
cp rcsf.out rcsf.inp
cp rcsf.out rcsfmr.inp
printf 'y' | rangular
rwfnestimate_input="rwfnestimate_input_1P1"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_1P1"
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
#rsave 1P1

#2. add active orbitals: layer 1-1 (5d)
rnucleus_input="rnucleus_input_Z70"
rnucleus < $rnucleus_input
cat $rnucleus_input
rcsfgenerate_input="rcsfgenerate_input_1P1_2"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log 1P1.exc
cp rcsf.out rcsf.inp
printf '1' | rcsfinteract
cp rcsf.out rcsf.inp
printf 'y' | rangular
rwfnestimate_input="rwfnestimate_input_1P1_2"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_1P1_2"
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
#rsave 1P1

#2. add active orbitals: layer 1-1 (7s)
rnucleus_input="rnucleus_input_Z70"
rnucleus < $rnucleus_input
cat $rnucleus_input
rcsfgenerate_input="rcsfgenerate_input_1P1_2"
rcsfgenerate < $rcsfgenerate_input
cat $rcsfgenerate_input
cp rcsfgenerate.log 1P1.exc
cp rcsf.out rcsf.inp
printf '1' | rcsfinteract
cp rcsf.out rcsf.inp
printf 'y' | rangular
rwfnestimate_input="rwfnestimate_input_1P1_2"
rwfnestimate < $rwfnestimate_input
cat $rwfnestimate_input
rmcdhf_input="rmcdhf_input_1P1_12"
rmcdhf < $rmcdhf_input
cat $rmcdhf_input
rsave 1P1

#3. add active orbitals: layer 1-2 (7p,5f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_3"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_3"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#3. add active orbitals: layer 1-3 (5g)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_4"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_4"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input

#4. add active orbitals: layer 2-1 (8s,6d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_5"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_5"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#5. add active orbitals: layer 2-2 (8p,6f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_6"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_6"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#6. add active orbitals: layer 3-1 (9p,7f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_7"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_7"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#7. add active orbitals: layer 3-2 (9s,7d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_8"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_8"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#8. add active orbitals: layer 3-2 (6g)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_9"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_9"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#9. add active orbitals: layer 4-1 (8d)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_10"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_10"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
#rsave 1P1

#10. add active orbitals: layer 4-1 (8f)
# rnucleus_input="rnucleus_input_Z70"
# rnucleus < $rnucleus_input
# cat $rnucleus_input
# rcsfgenerate_input="rcsfgenerate_input_1P1_11"
# rcsfgenerate < $rcsfgenerate_input
# cat $rcsfgenerate_input
# cp rcsfgenerate.log 1P1.exc
# cp rcsf.out rcsf.inp
# printf '1' | rcsfinteract
# cp rcsf.out rcsf.inp
# printf 'y' | rangular
# rwfnestimate_input="rwfnestimate_input_1P1_2"
# rwfnestimate < $rwfnestimate_input
# cat $rwfnestimate_input
# rmcdhf_input="rmcdhf_input_1P1_11"
# rmcdhf < $rmcdhf_input
# cat $rmcdhf_input
# rsave 1P1

stateID="1P1"
rsave $stateID
# printf "1\n$stateID.w\n$stateID.w.readrwf" | readrwf
printf "$stateID\nn\n0\ny" | rmixextract |& tee $stateID.rmix # DHF

# CI
rci_input="rci_input_1P1"
rci < $rci_input
cat $rci_input
#printf "$stateID\ny\n0\ny" | rmixextract |& tee $stateID.crmix # CI

# jj2lsj
jj2lsj_input="jj2lsj_input_1P1"
jj2lsj < $jj2lsj_input
cat $jj2lsj_input





